server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/praveenellaiyan/microservice-labs
          searchPaths: spring-cloud-config-props
          skipSslValidation: true
          clone-on-start: true
      label: master          