server:
  port: 8766
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.server.location}

zuul:
  routes:
    prefix: /movies
    movie-resource:
      path: /**
      serviceId: movie-service
