eureka:
  instance:
    hostname: localhost
  server:
    port: 8765
    location: http://${eureka.instance.hostname}:${eureka.server.port}/eureka

movies:
  gateway: 'api-gateway'
  all: '/movies/all'
  search: '/movies/search'
