server:
  port: 8091
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.server.location}
      
logging:
  file:
    name: D:/Github/Git/microservice-labs/app-data/logs/ms-movie-service.log