server:
  port: 8081

movies:
  gateway: ${movies.gateway}
  all: ${movies.all}
  search: ${movies.search}
  
          
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.server.location}
