server:
  port: 8081

movies:
  gateway: ${movies.gateway}
  all: ${movies.all}
  search: ${movies.search}
  
          
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.server.location}
      
logging:
  file:
    name: D:/Github/Git/microservice-labs/app-data/logs/ms-client-app.log
