eureka:
  instance:
    hostname: localhost
  server:
    port: 8765
    location: http://${eureka.instance.hostname}:${eureka.server.port}/eureka

movies:
  client: 'movie-service'
  all: '/movies/all'